apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app
  name: app
  namespace: stage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - image: kosmos38/13-kubernetes-frontend
          imagePullPolicy: IfNotPresent
          name: frontend
          env:
          - name: BASE_URL
            value: "http://backend:9000"
        - image: kosmos38/13-kubernetes-backend
          imagePullPolicy: IfNotPresent
          name: backend
          env:
          - name: DATABASE_URL
            value: "postgres://postgres:postgres@db:5432/news"
