apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backend
  name: backend
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - image: kosmos38/13-kubernetes-backend
          imagePullPolicy: IfNotPresent
          name: backend
          env:
          - name: DATABASE_URL
            value: "postgres://postgres:postgres@db:5432/news"