pipeline {
    agent { label 'ansible_docker' }

    stages {
        stage('1') {
            steps {
                // Get some code from a GitHub repository
                git credentialsId: '218dbf38-36d5-49b1-ab86-ea38fe3a8743', url: 'https://github.com/kosmos38/example-playbook'
            }
        }
        stage('2') {    
            steps {
                sh "ansible-vault decrypt secret --vault-password-file vault_pass && mkdir ~/.ssh && mv ./secret ~/.ssh/id_rsa && chmod 400 ~/.ssh/id_rsa"
            }
        }    
        stage('3') {    
            steps {
                sh '''echo "github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==" >> ~/.ssh/known_hosts'''
            }
        }
        stage('4') {
            steps {
                sh "ansible-galaxy install -r requirements.yml -p roles && ansible-playbook site.yml -i inventory/prod.yml"
            }
        }
        stage('5') {
            steps {
                sh "ls -lah roles"
            }
        }
    }
}