apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: static-nfs-pvc
  namespace: prod
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi